### ISSUE TITLE
Setup a favicon

### ISSUE THREAD

**Issue by mhelmetag** [learntocodesb/learntocodesb.github.io#1]
I love favicons. I bet you do too. Usually they're about 32x32 pixels (or maybe now they can be 64x64). It could be anything!

**Comment by mhelmetag** [comment]
So we now have a favicon but creating an original would still be nice!

**Comment by jemagee** [comment]
PS - you still need to add a date to publish the article I wrote if you want it published.  (I agree that a favicon that is original would be good but I just pulled something to do the pull request ;)

**Comment by mhelmetag** [comment]
Yep! Haven't merged master into gh-pages yet. Got distracted. Will do tonight.

**Comment by jemagee** [comment]
No problem - just saying that the date has to be added to the file name as well or jekyll treats it as the draft
